# version: "3.9"

services:
  backend:
    image: uzaifminfy/memepool-backend
    build:
      context: ./backend
    ports:
      - "5000:5000"
    

  frontend:
    image: uzaifminfy/memepool-frontend
    build:
      context: ./FrontEnd
    ports:
      - "5173:80"
    depends_on:
      - backend
    
