# version: "3.9"

services:
  backend:
    build:
      context: ./backend
    image: uzaifminfy/memepool-backend
    env_file:
      - .env
    ports:
      - "5000:5000"



  frontend:
    build:
      context: ./FrontEnd
    image: uzaifminfy/memepool-frontend
    env_file:
      - .env
    ports:
      - "5173:80"
    depends_on:
      - backend
