name: build-push

on:
  push:
    branches:
      - production

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: DockerHub Login
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build images using Docker Compose
      run: docker compose build

    - name: Push backend image to DockerHub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/memepool-backend

    - name: Push frontend image to DockerHub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/memepool-frontend
